language:
    - python

python:
    - '3.6'

install:
    - pip install -r requirements.txt
    - apt-get install libxml2-utils libxml2-dev

script:
    - ./harmony_hub.py
    - xmlint --noute profile/*/*.xml
